### ISSUE TITLE
Pitt Digital Library unsupported 

### ISSUE THREAD

**Issue by rbettoni** [indrimuska/zoomify#13]
Dear friends,

I don't know if this is the proper location to submit this - I did a lot of research and wasn't able to decide, I'm new to all of this.

The issue is that Digital Library of University of Pittsburg is not supported. I tried to use the addon in three different browsers. I also have tried to go the alternative way, searching for the link in the developer tab, but nothing really worked.

Thank you!

Here is an example: https://digital.library.pitt.edu/islandora/object/pitt%3Awmlp0056

**Comment by indrimuska** [comment]
You have to use the complete image.
See here: https://codesandbox.io/s/zoomify-pittsburg-example-7n5dko

**Comment by rbettoni** [comment]
Thank you very much
