### ISSUE TITLE
Zoomify-shadow above the image when using `animate.css`

### ISSUE THREAD

**Issue by Nishant-Rana** [indrimuska/zoomify#2]
Image Inside parent Div go behind zoomify-shadow div please look on this matter asap

**Comment by indrimuska** [comment]
Hi @Nishant-Rana, thank you for reporting this.
Can you please share the code you've tested for this issue, or alternatively provide a working example?

**Comment by Nishant-Rana** [comment]
Hi,
Here is the working link http://ruchirealty.com/kolkata/active-acres/index.php?id=home 
please the  zoomify-shadow background opacity you will notice my problem is

**Comment by Nishant-Rana** [comment]
In Features section

**Comment by indrimuska** [comment]
Ok, it seems that animate.css doesn't work very well with zoomify.
In your case, you can easily solve the issue using this piece of code:

``` css
#feature {
    -webkit-animation-fill-mode: none;
    animation-fill-mode: none;
}
```

I'm looking for a universal solution to overcome the problem.

**Comment by Nishant-Rana** [comment]
Thanks man it's really helpful it solve my purpose thanks again
